apiVersion: v1
kind: Pod
metadata:
  name: application-pod
  namespace: app-namespace
  labels:
    app: application
spec:
  containers:
  - name: application-container
    image: 309676119673.dkr.ecr.us-east-1.amazonaws.com/application:latest
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: 50.17.81.243
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DBPORT
      value: "3306"
    - name: APP_COLOR
      value: "blue"
    - name: DATABASE
      value: "employees"
  imagePullSecrets:
  - name: regcred
  
#Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ 
    
