apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: employees
  namespace: app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: application-container
        image: 309676119673.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: 54.196.228.111
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DBPORT
          value: "3306"
        - name: APP_COLOR
          value: "blue"
        - name: DATABASE
          value: "employees"
      imagePullSecrets:
      - name: regcred
